import { Game } from '../src/core/game.js';
import { BALANCE as B } from '../src/data/balance.js';
import { SAVE_KEY, createRun, defaultProgress, startLevel } from '../src/state/run.js';
import { stepRun } from '../src/systems/simulation.js';

const results = [];
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));

document.getElementById('start').addEventListener('click', async () => {
  const originalSave = localStorage.getItem(SAVE_KEY);
  const markup = await (await fetch('../index.html')).text();
  const template = new DOMParser().parseFromString(markup, 'text/html'); template.querySelectorAll('script').forEach(script => script.remove()); document.body.innerHTML = template.body.innerHTML;
  const style = document.createElement('link'); style.rel = 'stylesheet'; style.href = '../css/main.css'; document.head.append(style);
  const status = document.createElement('pre'); status.id = 'test-results'; status.style.cssText = 'position:fixed;right:12px;top:150px;max-width:520px;max-height:50vh;overflow:auto;background:#14251eef;padding:12px;font:11px monospace;white-space:pre-wrap;pointer-events:none;z-index:20'; document.body.append(status);
  const game = new Game(document.getElementById('game'));
  const report = async (name, fn) => { try { await fn(); results.push(`PASS ${name}`); } catch (error) { results.push(`FAIL ${name}: ${error.message}`); } status.textContent = results.join('\n'); };
  const render = () => { game.view.render(game.run, 0, true); game.hud.render(game.run, game.paused, game.started); };
  const tick = (count, input = {}) => { for (let i = 0; i < count; i++) stepRun(game.run, input, game.world, game.bus); render(); };

  try {
    game.resume(); await wait(150);
    await report('WebGL starts in the safe haven without errors', () => { assert(game.run.status === 'hub', 'not in hub'); assert(game.view.renderer.getContext().getError() === 0, 'WebGL error'); assert(game.hud.nodes['wave-name'].textContent === 'Home Camp', 'hub HUD'); });
    await report('play portal shows Start Here, biome locks, and six checkpoints', () => { game.run.progress.unlocked = { meadow: 20, frost: 0 }; game.run.progress.highest = { meadow: 17, frost: 0 }; game.hud.openMenu('play'); assert(document.querySelectorAll('.biome-card').length === 2, 'biome cards'); assert(document.querySelectorAll('.checkpoint[data-biome="meadow"]').length === 6, 'checkpoint count'); assert(document.querySelector('.start-here[data-biome="meadow"][data-wave="17"]'), 'highest-wave button missing'); assert(!document.querySelector('.checkpoint[data-biome="meadow"][data-wave="20"]').disabled, 'reached checkpoint locked'); assert(document.querySelector('.checkpoint[data-biome="meadow"][data-wave="30"]').disabled, 'future checkpoint open'); assert(document.querySelector('.checkpoint[data-biome="frost"][data-wave="1"]').disabled, 'frost open early'); game.hud.closeMenu(); });
    await report('hatchery circle, artwork, coins, and pet rendering stay complete', () => { assert(game.view.petPortal.children.length >= 3, 'hatchery circle incomplete'); game.run.coins = 2500; render(); assert(game.hud.nodes['coin-count'].textContent === '2,500', 'coin display incorrect'); game.hud.openMenu('pet-shop'); assert(document.querySelectorAll('.egg-card').length === 2, 'egg count'); assert(document.querySelectorAll('.egg-art').length === 2, 'egg artwork missing'); assert(document.querySelector('[data-egg-key="frost"]').disabled, 'frost egg unlocked early'); document.querySelector('[data-egg-key="meadow"]').click(); assert(game.run.pets.length === 1, 'pet did not hatch'); assert(game.run.coins === 2000, 'egg price incorrect'); assert(game.hud.nodes['coin-count'].textContent === '2,000', 'coin display did not refresh'); assert(!game.hud.nodes['hatch-result'].hidden, 'hatch reveal missing'); assert(document.querySelector('#hatch-result .pet-portrait'), 'hatch artwork missing'); game.hud.closeMenu(); game.hud.openMenu('pets'); const petCard = document.querySelector('[data-pet-id]'); assert(petCard?.querySelector('.pet-portrait'), 'pet card artwork missing'); petCard.click(); document.querySelector('[data-toggle-pet]').click(); assert(game.run.equippedPetIds.length === 1, 'pet did not equip'); game.hud.closeMenu(); render(); assert(game.view.petViews.size === 1, 'equipped pet not rendered'); });
    await report('index contains fifteen creatures and eleven gear sets', () => { game.hud.openMenu('index'); game.hud.indexTab = 'enemies'; game.hud.renderIndex(game.run); assert(document.querySelectorAll('#index-grid .index-card').length === 15, 'creature count'); game.hud.indexTab = 'sets'; game.hud.renderIndex(game.run); assert(document.querySelectorAll('#index-grid .index-card').length === 11, 'set count'); game.hud.closeMenu(); });
    await report('wave eight renders two models and two compact health rows', () => { game.run.progress.unlocked.meadow = 8; assert(startLevel(game.run, 'meadow', 8, game.world)); render(); assert(game.run.enemies.length === 2, 'enemy state count'); assert(game.view.enemyViews.size === 2, 'enemy view count'); assert(document.querySelectorAll('#enemy-list .enemy-row').length === 2, 'health row count'); assert(game.hud.nodes['wave-mode'].textContent.includes('2 animals'), 'enemy HUD count'); });
    await report('multi-target swing damages both visible enemies', () => { game.pause(); Object.assign(game.run.player, { x: 0, z: 0, facing: 0, attack: null }); game.run.enemies.forEach((enemy, index) => Object.assign(enemy, { x: index ? .35 : -.35, z: 1.4, health: 60, maxHealth: 60, mode: 'idle' })); const expected = 60 - game.run.player.damage; tick(12, { attack: true }); assert(game.run.enemies.every(enemy => enemy.health === expected), 'not all targets hit'); });
    await report('Spawn button abandons a wave without losing the highest wave', () => { const highest = game.run.progress.highest.meadow; document.getElementById('return-hub').click(); assert(game.run.status === 'hub', 'did not return'); assert(game.world.map.key === 'hub', 'hub collision map missing'); assert(game.run.progress.highest.meadow === highest, 'highest wave lost'); });
    await report('Frostfang switches to its own crystal arena and collision map', () => { game.run.progress.unlocked.frost = 1; assert(startLevel(game.run, 'frost', 1, game.world), 'frost did not start'); render(); assert(game.world.map.key === 'frost', 'frost collision map missing'); assert(game.view.frostDecor.visible, 'frost scenery hidden'); assert(!game.view.meadowDecor.visible, 'meadow scenery leaked into frost'); document.getElementById('return-hub').click(); });
    await report('inventory equips the best weapon and armor with one action per tab', () => { game.run.inventory = [{ id: 90, key: 'stone:sword', level: 1 }, { id: 91, key: 'jade:sword', level: 2 }, { id: 92, key: 'stone:helmet', level: 1 }, { id: 93, key: 'jade:helmet', level: 2 }]; game.hud.openMenu('inventory'); game.hud.inventoryTab = 'tools'; game.hud.renderInventory(game.run); document.getElementById('equip-best').click(); assert(game.run.equipped.weapon === 91, 'best weapon not equipped'); game.hud.inventoryTab = 'armor'; game.hud.renderInventory(game.run); document.getElementById('equip-best').click(); assert(game.run.equipped.helmet === 93, 'best armor not equipped'); game.hud.closeMenu(); });
    await report('upgrade screen combines matching items and refreshes stats', () => { game.run.inventory = [{ id: 100, key: 'stone:chestplate', level: 1 }, { id: 101, key: 'stone:chestplate', level: 1 }]; game.run.equipped = { chestplate: 100 }; game.hud.openMenu('upgrade'); const button = document.querySelector('[data-combine-key="stone:chestplate"]'); assert(button && !button.disabled, 'combine unavailable'); button.click(); assert(game.run.inventory.length === 1 && game.run.inventory[0].level === 2, 'combine failed'); assert(game.run.player.maxHealth > B.player.health, 'stats unchanged'); game.hud.closeMenu(); });
    await report('six spaced hub circles have labels and selling awards coins', () => { assert(game.view.portals.children.length === 6, 'portal count'); assert([...game.view.portals.children].every(portal => portal.children.some(child => child.isSprite)), 'portal label missing'); game.run.inventory = [{ id: 120, key: 'stone:sword', level: 1 }]; game.run.equipped = { weapon: 120 }; const coins = game.run.coins; game.hud.openMenu('sell-tools'); const sell = document.querySelector('[data-sell-id="120"]'); assert(sell, 'weapon not listed'); sell.click(); assert(game.run.inventory.length === 0, 'weapon not sold'); assert(game.run.coins > coins, 'coins not awarded'); game.hud.closeMenu(); });
    await report('fatal damage returns to hub and keeps upgraded gear', () => { game.run.inventory = [{ id: 125, key: 'stone:chestplate', level: 2 }]; game.run.equipped = { chestplate: 125 }; game.run.progress.unlocked.meadow = 8; startLevel(game.run, 'meadow', 8, game.world); game.run.player.health = 1; Object.assign(game.run.enemies[0], { x: game.run.player.x, z: game.run.player.z - 1, mode: 'windup', timer: 0, attackType: 'melee', range: B.enemy.reach }); tick(1); assert(game.run.status === 'hub', 'no hub return'); assert(game.run.inventory.length === 1 && game.run.inventory[0].level === 2, 'gear lost'); assert(game.run.player.health === game.run.player.maxHealth, 'not healed'); });
    await report('reload save schema retains inventory and checkpoint data', () => { game.run.inventory = [{ id: 130, key: 'stone:chestplate', level: 2 }]; game.save(); const loaded = JSON.parse(localStorage.getItem(SAVE_KEY)); assert(loaded.version === 4, 'save version'); assert(loaded.inventory[0].level === 2, 'upgrade not saved'); assert(loaded.unlocked.meadow === 8, 'checkpoint not saved'); });
  } finally {
    game.destroy(); if (originalSave === null) localStorage.removeItem(SAVE_KEY); else localStorage.setItem(SAVE_KEY, originalSave);
  }
  status.textContent = `${results.join('\n')}\n\n${results.filter(line => line.startsWith('PASS')).length}/${results.length} passed.`;
}, { once: true });
